# Generated by Django 4.1.8 on 2023-05-04 05:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='extensions.extension')),
                ('user', models.OneToOneField(help_text='The user that owns this account.', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('open', 'open'), ('paid', 'paid'), ('canceled', 'canceled'), ('failure', 'failure')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.account')),
                ('payment_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.account')),
            ],
            options={
                'verbose_name': 'historical invoice',
                'verbose_name_plural': 'historical invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalItemType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical item type',
                'verbose_name_plural': 'historical item types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalItemTypeCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item type category',
                'verbose_name_plural': 'historical item type categorys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('open', 'open'), ('paid', 'paid'), ('canceled', 'canceled'), ('failure', 'failure')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extensions.extension')),
                ('payment_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_out', to='payments.account')),
                ('payment_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_in', to='payments.account')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the item per unit.', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=1, help_text='The amount of units of the item.', max_digits=10)),
                ('invoice', models.ForeignKey(blank=True, help_text='The invoice this entry belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='extensions.extension')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='type',
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentprofile',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that owns this profile.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='date_started',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paymentprofile',
            name='user',
            field=models.OneToOneField(help_text='The user that owns this profile.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_started',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.itemtypecategory'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='itementry',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='The subscription this entry belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='itementry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.itemtype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='historicalitemtype',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.itemtypecategory'),
        ),
        migrations.AddField(
            model_name='historicalitemtype',
            name='extension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='historicalitemtype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='payment_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.account'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='payment_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_out', to='payments.account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_in', to='payments.account'),
        ),
    ]
