# Generated by Django 4.1.9 on 2023-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_account_historicalinvoice_historicalitemtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvoice',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='historicalpaymentprofile',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('sepa', 'Direct debit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentprofile',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('sepa', 'Direct debit')], max_length=30),
        ),
    ]
