# Generated by Django 4.1.10 on 2023-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_date_historicalinvoice_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitemtype',
            name='reference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalitemtypecategory',
            name='reference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='reference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemtypecategory',
            name='reference',
            field=models.IntegerField(null=True),
        ),
    ]
