# Generated by Django 4.1.3 on 2022-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtile',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
