# Generated by Django 4.1.9 on 2023-06-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
        ('core', '0002_coresettings_permission_historicalpermissiongroup_and_more'),
        ('dashboard', '0003_dashboardtilebutton_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtile',
            name='requires_group',
        ),
        migrations.RemoveField(
            model_name='historicaldashboardtile',
            name='requires_group',
        ),
        migrations.AddField(
            model_name='dashboardtile',
            name='requires_not_perm',
            field=models.ForeignKey(blank=True, help_text='If set, the object will only be displayed to users without this permission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requires_not_perm', to='core.permission'),
        ),
        migrations.AddField(
            model_name='dashboardtile',
            name='requires_perm',
            field=models.ForeignKey(blank=True, help_text='If set, the object will only be displayed to users with this permission.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requires_perm', to='core.permission'),
        ),
        migrations.AddField(
            model_name='dashboardtilebutton',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='historicaldashboardtile',
            name='requires_not_perm',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, the object will only be displayed to users without this permission.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.permission'),
        ),
        migrations.AddField(
            model_name='historicaldashboardtile',
            name='requires_perm',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, the object will only be displayed to users with this permission.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.permission'),
        ),
        migrations.AddField(
            model_name='historicaldashboardtilebutton',
            name='extension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardtilebutton',
            unique_together={('name', 'extension')},
        ),
    ]
