# Generated by Django 4.1.8 on 2023-05-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_permissiongroup_permissions'),
        ('dashboard', '0003_dashboardtilebutton_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtile',
            name='requires_group',
        ),
        migrations.RemoveField(
            model_name='historicaldashboardtile',
            name='requires_group',
        ),
        migrations.AddField(
            model_name='dashboardtile',
            name='requires_perm',
            field=models.ForeignKey(blank=True, help_text='If set, the object will only be displayed to users with this group.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.permission'),
        ),
        migrations.AddField(
            model_name='historicaldashboardtile',
            name='requires_perm',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, the object will only be displayed to users with this group.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.permission'),
        ),
    ]
