# Generated by Django 4.1.7 on 2023-03-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPayments',
            fields=[
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payments', serialize=False, to='memberships.membership')),
                ('shares_signed', models.IntegerField(default=0)),
            ],
        ),
    ]
