# Generated by Django 4.1.7 on 2023-03-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('memberships_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayments',
            name='fees_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_fees', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='membershippayments',
            name='shares_payments',
            field=models.ManyToManyField(blank=True, related_name='membership_shares', to='payments.payment'),
        ),
    ]
