# Generated by Django 4.1.9 on 2023-06-30 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extensions', '0001_initial'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipients',
            field=models.ManyToManyField(related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emails.emaildesign'),
        ),
        migrations.CreateModel(
            name='HistoricalEmailAutomation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this automation will be active and send emails.', verbose_name='Active')),
                ('description', models.TextField()),
                ('admin_only', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('admin_subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('admin_body', models.TextField(blank=True, verbose_name='Body')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin_design', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emaildesign', verbose_name='Design')),
                ('design', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emaildesign')),
                ('extension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='extensions.extension')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical email automation',
                'verbose_name_plural': 'historical email automations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmailAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this automation will be active and send emails.', verbose_name='Active')),
                ('description', models.TextField()),
                ('admin_only', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('admin_subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('admin_body', models.TextField(blank=True, verbose_name='Body')),
                ('admin_design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations_admin', to='emails.emaildesign', verbose_name='Design')),
                ('admin_recipients', models.ManyToManyField(blank=True, related_name='admin_email_automations', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations', to='emails.emaildesign')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.extension')),
            ],
            options={
                'unique_together': {('name', 'extension')},
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='automation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailautomation'),
        ),
        migrations.AddField(
            model_name='historicalemailcampaign',
            name='automation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emailautomation'),
        ),
    ]
