# Generated by Django 4.1.9 on 2023-06-15 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipients',
            field=models.ManyToManyField(related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
