# Generated by Django 4.2.3 on 2023-07-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailcampaign_recipients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailautomation',
            name='admin_body',
        ),
        migrations.RemoveField(
            model_name='emailautomation',
            name='admin_design',
        ),
        migrations.RemoveField(
            model_name='emailautomation',
            name='admin_subject',
        ),
        migrations.RemoveField(
            model_name='emailautomation',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailautomation',
            name='design',
        ),
        migrations.RemoveField(
            model_name='emailautomation',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='historicalemailautomation',
            name='admin_body',
        ),
        migrations.RemoveField(
            model_name='historicalemailautomation',
            name='admin_design',
        ),
        migrations.RemoveField(
            model_name='historicalemailautomation',
            name='admin_subject',
        ),
        migrations.RemoveField(
            model_name='historicalemailautomation',
            name='body',
        ),
        migrations.RemoveField(
            model_name='historicalemailautomation',
            name='design',
        ),
        migrations.RemoveField(
            model_name='historicalemailautomation',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='admin_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations_admin', to='emails.emailtemplate'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations', to='emails.emailtemplate'),
        ),
        migrations.AddField(
            model_name='historicalemailautomation',
            name='admin_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emailtemplate'),
        ),
        migrations.AddField(
            model_name='historicalemailautomation',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emailtemplate'),
        ),
    ]
