# Generated by Django 4.2.3 on 2023-07-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_remove_emailautomation_admin_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='historicalemailcampaign',
            name='automation',
        ),
    ]
