# Generated by Django 4.1.9 on 2023-06-20 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0003_alter_emailtemplate_design_historicalemailautomation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailautomation',
            name='admin_recipients',
            field=models.ManyToManyField(related_name='admin_email_automations', to=settings.AUTH_USER_MODEL),
        ),
    ]
