# Generated by Django 4.1.9 on 2023-06-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0004_emailautomation_admin_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_body',
            field=models.TextField(blank=True, verbose_name='Body (sent to admins)'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_recipients',
            field=models.ManyToManyField(blank=True, related_name='admin_email_automations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject (sent to admins)'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations', to='emails.emaildesign'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='admin_body',
            field=models.TextField(blank=True, verbose_name='Body (sent to admins)'),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='admin_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject (sent to admins)'),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
