# Generated by Django 4.2.3 on 2023-07-30 20:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0004_remove_emailcampaign_automation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSenderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique='True')),
                ('from_email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('host', models.CharField(max_length=255)),
                ('port', models.SmallIntegerField()),
                ('security_protocol', models.CharField(choices=[('none', 'none'), ('ssl', 'SSL'), ('tls', 'TLS')], default='none', max_length=4)),
                ('host_user', models.CharField(max_length=255)),
                ('host_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmailSenderConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('from_email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('host', models.CharField(max_length=255)),
                ('port', models.SmallIntegerField()),
                ('security_protocol', models.CharField(choices=[('none', 'none'), ('ssl', 'SSL'), ('tls', 'TLS')], default='none', max_length=4)),
                ('host_user', models.CharField(max_length=255)),
                ('host_password', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical email sender config',
                'verbose_name_plural': 'historical email sender configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sender_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailsenderconfig'),
        ),
        migrations.AddField(
            model_name='historicalemailtemplate',
            name='sender_config',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emailsenderconfig'),
        ),
    ]
