# Generated by Django 4.1.9 on 2023-06-21 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0005_alter_emailautomation_admin_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations_admin', to='emails.emaildesign', verbose_name='Design'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_recipients',
            field=models.ManyToManyField(blank=True, related_name='admin_email_automations', to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='admin_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailautomation',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If checked, this automation will be active and send emails.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='admin_body',
            field=models.TextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='admin_design',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='emails.emaildesign', verbose_name='Design'),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='admin_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='historicalemailautomation',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If checked, this automation will be active and send emails.', verbose_name='Active'),
        ),
    ]
