# Generated by Django 4.1.7 on 2023-03-26 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('person_type', models.CharField(choices=[('natural', 'natural'), ('legal', 'legal')], help_text='Type of person.', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('diverse', 'diverse'), ('female', 'female'), ('male', 'male')], max_length=50, null=True)),
                ('address_street', models.CharField(max_length=255)),
                ('address_number', models.CharField(max_length=255)),
                ('address_stair', models.CharField(blank=True, max_length=255)),
                ('address_door', models.CharField(blank=True, max_length=255)),
                ('address_postcode', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('legal_type', models.CharField(blank=True, max_length=255)),
                ('legal_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('person_type', models.CharField(choices=[('natural', 'natural'), ('legal', 'legal')], help_text='Type of person.', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('diverse', 'diverse'), ('female', 'female'), ('male', 'male')], max_length=50, null=True)),
                ('address_street', models.CharField(max_length=255)),
                ('address_number', models.CharField(max_length=255)),
                ('address_stair', models.CharField(blank=True, max_length=255)),
                ('address_door', models.CharField(blank=True, max_length=255)),
                ('address_postcode', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('legal_type', models.CharField(blank=True, max_length=255)),
                ('legal_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user profile',
                'verbose_name_plural': 'historical user profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
