# Generated by Django 4.1.9 on 2023-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='person_type',
            field=models.CharField(choices=[('natural', 'natural'), ('legal', 'legal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='person_type',
            field=models.CharField(choices=[('natural', 'natural'), ('legal', 'legal')], max_length=50, null=True),
        ),
    ]
