# Generated by Django 4.1.8 on 2023-05-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extensions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name of the component.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Description of the component and its features."
                        ),
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote Entry"),
                            ("iframe", "Iframe"),
                        ],
                        help_text="Type of the component.",
                        max_length=255,
                    ),
                ),
                (
                    "path",
                    models.URLField(
                        blank=True,
                        help_text=(
                            "URL of the remote entry point or iframe link."
                        ),
                    ),
                ),
                (
                    "extension",
                    models.ForeignKey(
                        blank=True,
                        help_text="The extension that this object belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ux_components",
                        to="extensions.extension",
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
    ]
