# Generated by Django 4.1.9 on 2023-06-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coresettings_permission_historicalpermissiongroup_and_more'),
        ('menus', '0002_alter_menuitem_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='component',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='requires_group',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='requires_perm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.permission'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='route',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target',
            field=models.CharField(choices=[('route', 'route'), ('link', 'link'), ('link_blank', 'link_blank')], default='route', max_length=50),
        ),
    ]
