# Generated by Django 4.1.8 on 2023-05-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_permissiongroup_permissions'),
        ('menus', '0002_alter_menuitem_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='requires_group',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='requires_perm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.permission'),
        ),
    ]
