# Generated by Django 4.1.7 on 2023-02-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_title', models.CharField(blank=True, max_length=30)),
                ('shift_starting_date', models.DateField(blank=True, null=True)),
                ('shift_ending_date', models.DateField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('regular', 'regular'), ('unique', 'unique')], default='fixed', help_text='Type of shift. Either shifts happen on a regular basis. Or they are unique and happen only once.', max_length=30)),
                ('shift_week', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', help_text='A month is divided in four shift weeks: A, B, C, D', max_length=1, null=True)),
                ('shift_starting_time', models.TimeField(blank=True, null=True)),
                ('shift_ending_time', models.TimeField(blank=True, null=True)),
                ('required_users', models.PositiveSmallIntegerField(default=2)),
                ('shift_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='MO', help_text='Shift days are necessary for fixed shifts to registeri.e. every monday on Week A', max_length=10, null=True)),
                ('additional_info_general', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('creator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('additional_info_individual', models.TextField(max_length=300)),
                ('assigned_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftuser')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
        ),
    ]
