# Generated by Django 4.1.7 on 2023-03-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_title', models.CharField(blank=True, max_length=30)),
                ('shift_starting_date', models.DateField(blank=True, null=True)),
                ('shift_ending_date', models.DateField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('regular', 'regular'), ('unique', 'unique')], default='fixed', help_text='Type of shift. Either shifts happen on a regular basis. Or they are unique and happen only once.', max_length=30)),
                ('shift_week', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', help_text='A month is divided in four shift weeks: A, B, C, D', max_length=1, null=True)),
                ('shift_starting_time', models.TimeField(blank=True, null=True)),
                ('shift_ending_time', models.TimeField(blank=True, null=True)),
                ('required_users', models.PositiveSmallIntegerField(default=2)),
                ('shift_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='MO', help_text='Shift days are necessary for fixed shifts to registeri.e. every monday on Week A', max_length=10, null=True)),
                ('additional_info_general', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('additional_info_individual', models.TextField(max_length=300)),
                ('assigned_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shiftprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalShiftProfile',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift profile',
                'verbose_name_plural': 'historical shift profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShiftAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('additional_info_individual', models.TextField(max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shifts.shiftprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'historical shift assignment',
                'verbose_name_plural': 'historical shift assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('shift_title', models.CharField(blank=True, max_length=30)),
                ('shift_starting_date', models.DateField(blank=True, null=True)),
                ('shift_ending_date', models.DateField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('regular', 'regular'), ('unique', 'unique')], default='fixed', help_text='Type of shift. Either shifts happen on a regular basis. Or they are unique and happen only once.', max_length=30)),
                ('shift_week', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', help_text='A month is divided in four shift weeks: A, B, C, D', max_length=1, null=True)),
                ('shift_starting_time', models.TimeField(blank=True, null=True)),
                ('shift_ending_time', models.TimeField(blank=True, null=True)),
                ('required_users', models.PositiveSmallIntegerField(default=2)),
                ('shift_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='MO', help_text='Shift days are necessary for fixed shifts to registeri.e. every monday on Week A', max_length=10, null=True)),
                ('additional_info_general', models.TextField(blank=True, max_length=300, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift',
                'verbose_name_plural': 'historical shifts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
