# Generated by Django 4.1.7 on 2023-04-04 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshiftprofile',
            name='shift_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftprofile',
            name='shift_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift'),
        ),
        migrations.AlterField(
            model_name='shiftprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shift_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
