# Generated by Django 4.1.7 on 2023-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_historicalshiftprofile_shift_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='shift_type',
            field=models.CharField(choices=[('regular', 'regular'), ('repeating_weekly', 'repeating_weekly'), ('repeating_monthly', 'repeating_monthly'), ('extra', 'extra'), ('holiday', 'holiday'), ('other', 'other')], default='fixed', help_text='Type of shift. Regular shifts are one time shifts. Repeating shifts can beweekly or monthly. Extra shifts are shifts that are not part of theregular schedule. Holiday shifts are shifts that are not part of theregular schedule but are not extra shifts. Other shifts are shifts thatare not part of the regular schedule and are not extra shifts and are notholiday shifts.', max_length=30),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('regular', 'regular'), ('repeating_weekly', 'repeating_weekly'), ('repeating_monthly', 'repeating_monthly'), ('extra', 'extra'), ('holiday', 'holiday'), ('other', 'other')], default='fixed', help_text='Type of shift. Regular shifts are one time shifts. Repeating shifts can beweekly or monthly. Extra shifts are shifts that are not part of theregular schedule. Holiday shifts are shifts that are not part of theregular schedule but are not extra shifts. Other shifts are shifts thatare not part of the regular schedule and are not extra shifts and are notholiday shifts.', max_length=30),
        ),
    ]
