# Generated by Django 4.1.7 on 2023-03-29 10:45

import collectivo.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the extension.', max_length=255, unique=True)),
                ('label', models.CharField(blank=True, help_text='Label to display the extension.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the extension and its features.')),
                ('built_in', models.BooleanField(default=False, help_text='Whether the extension is part of collectivo.')),
                ('version', models.CharField(blank=True, help_text='Version of the extension.', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Whether the extension is active.')),
            ],
            bases=(models.Model, collectivo.utils.models.RegisterMixin),
        ),
    ]
