# Generated by Django 4.1.2 on 2022-10-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
