# Generated by Django 4.1.3 on 2022-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_extension_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='built_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extension',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
