# Generated by Django 4.1.9 on 2023-06-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coresettings_permission_historicalpermissiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermission',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpermissiongroup',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='permission',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
