# Generated by Django 4.1.8 on 2023-05-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coresettings_endpoint_historicalpermissiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='core.permission'),
        ),
    ]
