# Generated by Django 4.1.9 on 2023-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coresettings_permission_historicalpermissiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='project_logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/logo/'),
        ),
        migrations.AddField(
            model_name='historicalcoresettings',
            name='project_logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
