# Generated by Django 4.1.10 on 2023-07-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalpermission_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresettings',
            name='display_project_name',
            field=models.BooleanField(default=False, verbose_name='Display project name'),
        ),
        migrations.AlterField(
            model_name='historicalcoresettings',
            name='display_project_name',
            field=models.BooleanField(default=False, verbose_name='Display project name'),
        ),
    ]
