# Generated by Django 4.1.9 on 2023-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coresettings_project_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='project_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcoresettings',
            name='project_logo_url',
            field=models.URLField(blank=True),
        ),
    ]
