# Generated by Django 4.1.8 on 2023-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permissiongroup_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.permission'),
        ),
    ]
