# Generated by Django 4.1.9 on 2023-06-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coresettings_project_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='display_project_description',
            field=models.BooleanField(default=False, verbose_name='Display project description'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='display_project_logo',
            field=models.BooleanField(default=True, verbose_name='Display project logo'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='display_project_name',
            field=models.BooleanField(default=True, verbose_name='Display project name'),
        ),
        migrations.AddField(
            model_name='historicalcoresettings',
            name='display_project_description',
            field=models.BooleanField(default=False, verbose_name='Display project description'),
        ),
        migrations.AddField(
            model_name='historicalcoresettings',
            name='display_project_logo',
            field=models.BooleanField(default=True, verbose_name='Display project logo'),
        ),
        migrations.AddField(
            model_name='historicalcoresettings',
            name='display_project_name',
            field=models.BooleanField(default=True, verbose_name='Display project name'),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='project_logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/logo/', verbose_name='Project logo (File upload)'),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='project_logo_url',
            field=models.URLField(blank=True, verbose_name='Project logo (URL)'),
        ),
        migrations.AlterField(
            model_name='coresettings',
            name='project_name',
            field=models.CharField(blank=True, default='My community plattform', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcoresettings',
            name='project_logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Project logo (File upload)'),
        ),
        migrations.AlterField(
            model_name='historicalcoresettings',
            name='project_logo_url',
            field=models.URLField(blank=True, verbose_name='Project logo (URL)'),
        ),
        migrations.AlterField(
            model_name='historicalcoresettings',
            name='project_name',
            field=models.CharField(blank=True, default='My community plattform', max_length=255),
        ),
    ]
