# Generated by Django 4.1.2 on 2022-10-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0002_extension_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroFrontend',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('path', models.URLField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.extension')),
            ],
        ),
    ]
