# Generated by Django 4.1.2 on 2022-10-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0002_alter_microfrontend_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microfrontend',
            name='path',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
