# Generated by Django 4.1.2 on 2022-10-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_extension_description'),
        ('ux', '0005_menu_remove_microfrontend_method_microfrontend_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='microfrontend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ux.microfrontend'),
        ),
        migrations.AlterField(
            model_name='microfrontend',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
    ]
