# Generated by Django 4.1.2 on 2022-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0006_alter_menu_extension_alter_menuitem_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='action',
            field=models.CharField(choices=[('default', 'Render microfrontend in the main application window.'), ('blank', 'Render microfrontend in a new page.')], default='default', max_length=50),
        ),
    ]
