# Generated by Django 4.1.2 on 2022-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0008_alter_menuitem_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='action',
            field=models.CharField(choices=[('default', 'default'), ('blank', 'blank')], default='default', max_length=50),
        ),
    ]
