# Generated by Django 4.1.3 on 2022-11-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0009_alter_menuitem_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='microfrontend',
        ),
        migrations.DeleteModel(
            name='MicroFrontend',
        ),
    ]
