# Generated by Django 4.1.3 on 2022-11-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_extension_built_in_alter_extension_version'),
        ('ux', '0011_rename_name_menu_menu_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='action_target',
            field=models.CharField(choices=[('main', 'main'), ('blank', 'blank')], default='main', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='component_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon_path',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_source',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ux.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='required_role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='style',
            field=models.CharField(choices=[('normal', 'normal')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='action',
            field=models.CharField(choices=[('component', 'component'), ('link', 'link')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.extension'),
        ),
    ]
