# Generated by Django 4.1.3 on 2022-11-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('built_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(choices=[('child', 'child'), ('coshopper', 'coshopper')], max_length=20)),
                ('birth_date', models.DateField(null=True)),
                ('membership_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membercard')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(choices=[('natural', 'natural'), ('legal', 'legal')], default='natural', help_text='Type of person.', max_length=20)),
                ('gender', models.CharField(choices=[('diverse', 'diverse'), ('female', 'female'), ('male', 'male')], default='diverse', max_length=20)),
                ('address_street', models.CharField(max_length=255, null=True)),
                ('address_number', models.CharField(max_length=255, null=True)),
                ('address_stair', models.CharField(max_length=255, null=True)),
                ('address_door', models.CharField(max_length=255, null=True)),
                ('address_postcode', models.CharField(max_length=255, null=True)),
                ('address_city', models.CharField(max_length=255, null=True)),
                ('address_country', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('birthday', models.DateField(null=True)),
                ('legal_name', models.CharField(max_length=255, null=True)),
                ('legal_type', models.CharField(max_length=255, null=True)),
                ('legal_id', models.CharField(max_length=255, null=True)),
                ('membership_start', models.DateField(null=True)),
                ('membership_cancelled', models.DateField(null=True)),
                ('membership_end', models.DateField(null=True)),
                ('membership_status', models.CharField(choices=[('applicant', 'applicant'), ('provisional', 'provisional'), ('active', 'active'), ('investing', 'investing'), ('ended', 'ended')], default='1_applicant', help_text='Current status of membership.', max_length=20)),
                ('shares_number', models.IntegerField(null=True)),
                ('shares_payment_date', models.DateField(null=True)),
                ('shares_payment_type', models.CharField(choices=[('sepa', 'sepa'), ('transfer', 'transfer')], help_text='Type of payment.', max_length=20, null=True)),
                ('bank_account_iban', models.CharField(max_length=255, null=True)),
                ('bank_account_owner', models.CharField(max_length=255, null=True)),
                ('survey_first_heard', models.TextField(null=True)),
                ('survey_motivation', models.TextField(null=True)),
                ('survey_working_groups', models.TextField(null=True)),
                ('survey_skills', models.TextField(null=True)),
                ('admin_notes', models.TextField(null=True)),
                ('membership_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membercard')),
                ('tags', models.ManyToManyField(to='members.membertag')),
            ],
        ),
    ]
