# Generated by Django 4.1.2 on 2022-10-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
