# Generated by Django 4.1.3 on 2022-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='children', to='members.memberaddon'),
        ),
        migrations.AlterField(
            model_name='member',
            name='coshoppers',
            field=models.ManyToManyField(blank=True, related_name='coshoppers', to='members.memberaddon'),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='members.membergroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups_interested',
            field=models.ManyToManyField(blank=True, related_name='groups_interested', to='members.membergroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(blank=True, to='members.memberskill'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, to='members.membertag'),
        ),
    ]
