# Generated by Django 4.1.5 on 2023-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertag',
            name='built_in',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
