# Generated by Django 4.1.3 on 2022-11-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email_verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='family_name',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='given_name',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
