# Generated by Django 4.1.3 on 2022-12-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_children_alter_member_coshoppers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.memberstatus'),
        ),
    ]
