# Generated by Django 4.1.3 on 2022-11-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('diverse', 'diverse'), ('female', 'female'), ('male', 'male')], max_length=20, null=True),
        ),
    ]
