# Generated by Django 4.1.3 on 2022-11-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_email_member_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='family_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='given_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
