# Generated by Django 4.1.3 on 2022-11-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('built_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='address_co',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address_is_home',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='member',
            name='legal_seat',
        ),
        migrations.RemoveField(
            model_name='member',
            name='legal_type_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='shares_installment_plan',
        ),
        migrations.RemoveField(
            model_name='member',
            name='shares_payment_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title_post',
        ),
        migrations.RemoveField(
            model_name='member',
            name='title_pre',
        ),
        migrations.AddField(
            model_name='member',
            name='admin_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bank_account_iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bank_account_owner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='legal_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_cancelled_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_ended_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_started_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='person_type',
            field=models.CharField(choices=[('natural', 'natural'), ('legal', 'legal')], default='natural', help_text='Type of person.', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='shares_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_first_heard',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_motivation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='survey_working_groups',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('diverse', 'diverse'), ('female', 'female'), ('male', 'male')], default='diverse', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('1_applicant', '1_applicant'), ('2_active', '2_active'), ('3_investing', '3_investing'), ('4_ended', '4_ended')], default='1_applicant', help_text='Current status of membership.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='shares_payment_type',
            field=models.CharField(choices=[('sepa', 'sepa'), ('transfer', 'transfer')], default='sepa', help_text='Type of payment.', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(choices=[('child', 'child'), ('coshopper', 'coshopper')], max_length=20)),
                ('birth_date', models.DateField(null=True)),
                ('membership_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membercard')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membercard'),
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(to='members.membertag'),
        ),
    ]
