# Generated by Django 4.1.9 on 2023-06-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
        ('memberships', '0003_historicalmembership_date_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipEmails',
            fields=[
                ('membership_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emails', serialize=False, to='memberships.membershiptype')),
                ('template_accepted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_accepted', to='emails.emailtemplate')),
                ('template_ended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_ended', to='emails.emailtemplate')),
                ('template_started', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_started', to='emails.emailtemplate')),
            ],
        ),
    ]
