# Generated by Django 4.1.7 on 2023-02-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectivo_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='label',
            new_name='name',
        ),
    ]
