# Generated by Django 4.1.7 on 2023-03-29 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_shares', models.BooleanField(default=False, help_text='Whether users need to buy shares to become members.')),
                ('shares_amount_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='The amount of money that has to be paid per share.', max_digits=100, null=True)),
                ('shares_number_custom', models.BooleanField(default=False, help_text='Whether members can choose a custom number of shares.')),
                ('shares_number_custom_min', models.IntegerField(blank=True, help_text='The minimum number of shares for custom numbers of shares.', null=True)),
                ('shares_number_custom_max', models.IntegerField(blank=True, help_text='The maximum number of shares for custom numbers of shares.', null=True)),
                ('shares_number_standard', models.IntegerField(blank=True, help_text='The default number of shares.', null=True)),
                ('shares_number_social', models.IntegerField(blank=True, help_text='A reduced number of shares.', null=True)),
                ('has_fees', models.BooleanField(default=False)),
                ('fees_amount_custom', models.BooleanField(default=False)),
                ('fees_amount_custom_min', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_custom_max', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_social', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_repeat_each', models.IntegerField(default=1)),
                ('fees_repeat_unit', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], default='year', max_length=20)),
                ('currency', models.CharField(default='EUR', help_text='The currency used for fees and shares.', max_length=3)),
                ('comembership_max', models.IntegerField(blank=True, null=True)),
                ('comembership_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membershiptype')),
                ('statuses', models.ManyToManyField(blank=True, help_text='The statuses that a membership of this type can have.', to='memberships.membershipstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Membership number')),
                ('date_started', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date_cancelled', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('shares_signed', models.PositiveIntegerField(default=0)),
                ('shares_paid', models.PositiveIntegerField(default=0)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('comembership_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membership')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='memberships.membershipstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershiptype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('number', 'type')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalMembershipType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_shares', models.BooleanField(default=False, help_text='Whether users need to buy shares to become members.')),
                ('shares_amount_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='The amount of money that has to be paid per share.', max_digits=100, null=True)),
                ('shares_number_custom', models.BooleanField(default=False, help_text='Whether members can choose a custom number of shares.')),
                ('shares_number_custom_min', models.IntegerField(blank=True, help_text='The minimum number of shares for custom numbers of shares.', null=True)),
                ('shares_number_custom_max', models.IntegerField(blank=True, help_text='The maximum number of shares for custom numbers of shares.', null=True)),
                ('shares_number_standard', models.IntegerField(blank=True, help_text='The default number of shares.', null=True)),
                ('shares_number_social', models.IntegerField(blank=True, help_text='A reduced number of shares.', null=True)),
                ('has_fees', models.BooleanField(default=False)),
                ('fees_amount_custom', models.BooleanField(default=False)),
                ('fees_amount_custom_min', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_custom_max', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_standard', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_amount_social', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fees_repeat_each', models.IntegerField(default=1)),
                ('fees_repeat_unit', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('week', 'week'), ('day', 'day')], default='year', max_length=20)),
                ('currency', models.CharField(default='EUR', help_text='The currency used for fees and shares.', max_length=3)),
                ('comembership_max', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comembership_of', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='memberships.membershiptype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical membership type',
                'verbose_name_plural': 'historical membership types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical membership status',
                'verbose_name_plural': 'historical membership statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Membership number')),
                ('date_started', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date_cancelled', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('shares_signed', models.PositiveIntegerField(default=0)),
                ('shares_paid', models.PositiveIntegerField(default=0)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comembership_of', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='memberships.membership')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='memberships.membershipstatus')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='memberships.membershiptype')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical membership',
                'verbose_name_plural': 'historical memberships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
