# Generated by Django 4.1.7 on 2023-04-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmembership',
            name='shares_paid',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='shares_paid',
        ),
    ]
