# Generated by Django 4.1.9 on 2023-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_remove_historicalmembership_shares_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembership',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='shares_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='shares_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
