# Generated by Django 4.1.9 on 2023-06-21 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0002_remove_historicalmembership_shares_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmembership',
            old_name='date_started',
            new_name='date_applied',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='date_started',
            new_name='date_applied',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'type'), ('number', 'type')},
        ),
        migrations.RemoveField(
            model_name='historicalmembership',
            name='date_cancelled',
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='date_excluded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='date_resigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='shares_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmembership',
            name='stage',
            field=models.CharField(choices=[('applied', 'applied'), ('accepted', 'accepted'), ('resigned', 'resigned'), ('excluded', 'excluded'), ('ended', 'ended')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalmembershiptype',
            name='enable_registration',
            field=models.BooleanField(default=False, help_text='Whether users can register for this membership type.', verbose_name='Enable registration'),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_excluded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_resigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='shares_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='stage',
            field=models.CharField(choices=[('applied', 'applied'), ('accepted', 'accepted'), ('resigned', 'resigned'), ('excluded', 'excluded'), ('ended', 'ended')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='enable_registration',
            field=models.BooleanField(default=False, help_text='Whether users can register for this membership type.', verbose_name='Enable registration'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='date_cancelled',
        ),
    ]
